# Uncomment the next line to define a global platform for your project
 platform :ios, '9.3'

target 'CollageKid' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CollageKid

	rn_path = '../node_modules/react-native'
  	pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  	pod 'React', path: rn_path, subspecs: [
    		'Core',
    		'RCTActionSheet',
    		'RCTAnimation',
    		'RCTGeolocation',
    		'RCTImage',
    		'RCTLinkingIOS',
    		'RCTNetwork',
    		'RCTSettings',
    		'RCTText',
    		'RCTVibration',
    		'RCTWebSocket'
  	]

  	pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  target 'CollageKidTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

target 'CollageKid test bundleID' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CollageKid test bundleID

end

target 'CollageKid-nobundleserver' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CollageKid-nobundleserver

end

target 'CollageKid-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CollageKid-tvOS

  target 'CollageKid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
